check_task:
  container:
    image: fnichol/check-shell:latest
  check_script: make check

task:
  env:
    matrix:
      - SHELL_BIN: apple-bash-23
      - SHELL_BIN: apple-bash-44
      - SHELL_BIN: apple-bash-76
      - SHELL_BIN: apple-bash-94
      - SHELL_BIN: apple-bash-106.220
      - SHELL_BIN: bash-2
      - SHELL_BIN: bash-3
      - SHELL_BIN: bash-3.00
      - SHELL_BIN: bash-4
      - SHELL_BIN: bash-5
      - SHELL_BIN: busybox-1.23.2-ash
      - SHELL_BIN: busybox-1.30.1-ash
      - SHELL_BIN: dash-0
      - SHELL_BIN: dash-0.5.10.2
      - SHELL_BIN: ksh93-2008-07-25
      - SHELL_BIN: ksh93-2012-08-01
      # - SHELL_BIN: zsh-3
      # - SHELL_BIN: zsh-4
      - SHELL_BIN: zsh-5
  name: test_$SHELL_BIN
  container:
    dockerfile: .ci/Dockerfile.ci
  test_script: make test
