#!/usr/bin/env sh
# shellcheck disable=SC2039

. "lib/check_cmd.sh"
. "lib/cleanup_directory.sh"
. "lib/cleanup_file.sh"
. "lib/die.sh"
. "lib/download.sh"
. "lib/indent.sh"
. "lib/info.sh"
. "lib/info_end.sh"
. "lib/info_start.sh"
. "lib/mktemp_directory.sh"
. "lib/mktemp_file.sh"
. "lib/need_cmd.sh"
. "lib/print_version.sh"
. "lib/section.sh"
. "lib/setup_cleanup_directories.sh"
. "lib/setup_cleanup_files.sh"
. "lib/setup_cleanups.sh"
. "lib/setup_traps.sh"
. "lib/trap_cleanup_directories.sh"
. "lib/trap_cleanup_files.sh"
. "lib/trap_cleanups.sh"
. "lib/warn.sh"
